server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students-microservice
          uri: lb://students-microservice
          predicates:
            - Path=/students/**
        - id: exams-microservice
          uri: lb://exams-microservice
          predicates:
            - Path=/exams/**
